### ISSUE TITLE
Classic Era / SoD - Arcane Intellect Next Rank Available at 0 when no target

### ISSUE THREAD

**Issue by boktai1000** [valkyrnstudios/RankSentinel#86]
https://legacy.curseforge.com/wow/addons/ranksentinel?comment=76

On SoD when I target myself and cast a low rank of AI it seems to detect fine, but when I don't have myself targetted and cast it says that the next rank is available at 0

![image](https://github.com/valkyrnstudios/RankSentinel/assets/9054563/a4ed7634-204d-45bf-aa9d-9c92479e5969)

**Comment by SabreValkyrn** [comment]
Does this repro with the latest alpha?

**Comment by boktai1000** [comment]
Just re-tested on my (now level 17) mage using Rank 1 AI, seems like it works as expected and no next rank at 0 message :)

![image](https://github.com/valkyrnstudios/RankSentinel/assets/9054563/3a2a2c8a-c60b-4cc3-a1e1-0c244b2914b9)

Only thing is, and this might be intended behavior - I could not get the message to re-pop after dropping the buff, relogging and reloading. Perhaps its just been a while, or maybe something else - but at least as far as rank 0 goes - seems to be fixed and working as expected here :)

**Comment by SabreValkyrn** [comment]
> Just re-tested on my (now level 17) mage using Rank 1 AI, seems like it works as expected and no next rank at 0 message

Yay, glad to see [141 commits](https://github.com/valkyrnstudios/RankSentinel/compare/v1.4.1...main) since the last Classic release fixed something :joy:

> I could not get the message to re-pop after dropping the buff, relogging and reloading.

That's correct, it only notifies once per `player-spellID-level` combination by caching notifications. Cache gets purged on addon updates or with `/sentinel clear` https://github.com/valkyrnstudios/RankSentinel/blob/d2748703b857b6c2cd0e2bfd21bc5f3323771ba4/RankSentinel.lua#L182

The GUI UI was added after the fact so it's missing some of the more nuanced or advanced settings/toggles.
